version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - "./src/.env"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db
    networks:
      - local-net
  db:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    networks:
      - local-net

volumes:
  postgres_data:

networks:
  local-net:
    driver: bridge
